### ISSUE TITLE
Practica 1 Reporte de App de Realidad AumentadaTarea

### ISSUE THREAD

**Issue by JeserLeonel** [SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-JeserLeonel#2]
[Practica 1 Reporte de App de Realidad AumentadaTarea.pdf](https://github.com/SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-JeserLeonel/files/8127133/Practica.1.Reporte.de.App.de.Realidad.AumentadaTarea.pdf)

**Comment by CarlosSD16** [comment]
falto justificar texto y en todo los demás se cumple con lo requeridos
calificación:18

**Comment by josealfredo79** [comment]
Bien hecho y revisado
